package it.linksmt.assatti.bpm.util;

public interface AttoProcessVariables {

	String ID_ATTO 			= "ID_ATTO";
	String ROLLBACK_INFO	="ROLLBACK_INFO";
	String ROLLBACK_ENABLED	="ROLLBACK_ENABLED";
	String TIPO_ATTO 		= "TIPO_ATTO";
	String OGGETTO_ATTO 	= "OGGETTO_ATTO";
	String TIPO_ITER 		= "TIPO_ITER";
	
	String ISTRUTTORE_ATTO	= "ISTRUTTORE_ATTO";
	String AOO_CODICE		= "AOO_CODICE";
	String AOO_DESCRIZIONE	= "AOO_DESCRIZIONE";
	
	String LISTA_DECISIONI			= "LISTA_DECISIONI";
	String SCENARI_DISABILITAZIONE	= "SCENARI_DISABILITAZIONE";
	String ASSEGNAZIONE_INCARICHI 	= "ASSEGNAZIONE_INCARICHI";
	
	String DELEGA_TASK_FULL_ITER = "DELEGA_TASK_FULL_ITER";
	String DELEGA_ONE_TASK_ONLY = "DELEGA_ONE_TASK_ONLY";
	String PROFILO_DELEGANTE	= "PROFILO_DELEGANTE";
	
	//contiene l'assegnatario originario in caso di riassegnazione task
	String PROFILO_ORIGINARIO	= "PROFILO_ORIGINARIO";
	
	String DELEGA_SINGOLA_LAVORAZIONE	= "DELEGA_SINGOLA_LAVORAZIONE";
	String ASSESSORE_VISTO		= "ASSESSORE_VISTO";
	
	String TIPO_FINE_ITER	= "TIPO_FINE_ITER";
	
	String MULTI_DELEGATES_LIST = "DELEGATES_LIST";
	
	String IMPOSTA_STATO	= "IMPOSTA_STATO";
	String REGISTRA_EVENTO 	= "REGISTRA_EVENTO";
	String AZIONE_UTENTE	= "AZIONE_UTENTE";
	
	String COM_CONSQUART_REVCONT_EDITABLE = "COM_CONSQUART_REVCONT_EDITABLE";
	
	String ESITO_PROPOSTA_ODG	= "ESITO_PROPOSTA_ODG";
	String SEGRETARIO_SEDUTA	= "SEGRETARIO_SEDUTA";
	String PRESIDENTE_SEDUTA	= "PRESIDENTE_SEDUTA";
	
	String GENERAZIONE_DOCUMENTO_OMISSIS = "GENERAZIONE_DOCUMENTO_OMISSIS"; // booleano
	String GENERAZIONE_DOCUMENTO_FIRMATO = "GENERAZIONE_DOCUMENTO_FIRMATO"; // ordine di inclusione degli allegati
	String GENERAZIONE_DOCUMENTO_FIRMATO_DA_TUTTI = "GENERAZIONE_DOCUMENTO_FIRMATO_DA_TUTTI"; // booleano: se true il documentoinformatico da salvare è un allegato
	
	String LISTA_DOCUMENTI_ANTEPRIMA 	= "LISTA_DOCUMENTI_ANTEPRIMA"; // elenco dei codici dei tipi di documento per i quali si vuole visualizzare una preview in uno specifico task
	String LISTA_DOCUMENTI_GENERAZIONE	= "LISTA_DOCUMENTI_GENERAZIONE";	// elenco dei codici dei tipi di documento da generare in uno specifico task
	String LISTA_DOCUMENTI_FIRMA 		= "LISTA_DOCUMENTI_FIRMA";	 		// elenco dei codici dei tipi di documento da firmare in uno specifico task
	
	String VAR_ATTO_IN_RAGIONERIA   = "ATTO_IN_RAGIONERIA";
	String VAR_ATTO_IN_PREDISPOSIZIONE = "ATTO_IN_PREDISPOSIZIONE";
	String RISERVATO				= "RISERVATO";

	// Processi di supporto (es. visto Assessore, visto Consigliere)
	String START_PROCESS_COLLECTION 		= "START_PROCESS_COLLECTION";
	String START_PROCESS_ELEMENT_VARIABLE	= "START_PROCESS_ELEMENT_VARIABLE";
	String START_PROCESS_DEFINITION_KEY		= "START_PROCESS_DEFINITION_KEY";
	
	String VAR_RIGENERAZIONE_DOCUMENTO   = "RIGENERAZIONE_DOCUMENTO";
	
	// Task Massivi
	String TASK_OPERAZIONE_MASSIVA_SEP = "::";
	String TASK_OPERAZIONE_MASSIVA	= "ABILITA_OPERAZIONE_MASSIVA";
	String TASK_VAL_VISTO_MASSIVO	= "VISTO_MASSIVO";
	String TASK_VAL_FIRMA_MASSIVA	= "FIRMA_MASSIVA";
	String TASK_VAL_FIRMA_ATTO = "FIRMA_ATTO";
	String TASK_VAL_NUMERA_GENERA_FIRMA_ATTO = "NUMERA_GENERA_FIRMA_ATTO";
	String TASK_VAL_GENERA_FIRMA_ATTO = "GENERA_FIRMA_ATTO";
	String TASK_VAL_GENERA_FIRMA_REG_CONT = "GENERA_FIRMA_REG_CONT";
	String TASK_VAL_GENERA_FIRMA_REG_TECN = "GENERA_FIRMA_REG_TECN";
	String TASK_VAL_FIRMA_REG_TECN = "FIRMA_REG_TECN";
}
