package it.linksmt.assatti.bpm.util;;

public interface CodiciAzioniUtente {
	String GENERA_FIRMA_ATTO	= "GENERA_FIRMA_ATTO";
	String GENERA_ATTO 			= "GENERA_ATTO";
	String VISTO_POSITIVO_GENERA_ATTO 	= "VISTO_POSITIVO_GENERA_ATTO";
	String GENERA_PAR_REG		= "GENERA_PAR_REG";
	String GENERA_ATTO_DL		= "GENERA_ATTO_DL";
	String VISTO_POSITIVO_GENERA_ATTO_DL = "VISTO_POSITIVO_GENERA_ATTO_DL";
	String NUMERA_E_GENERA_ATTO = "NUMERA_E_GENERA_ATTO";
	String FIRMA_ATTO 			= "FIRMA_ATTO";
	String NUMERA_GENERA_FIRMA_ATTO = "NUMERA_GENERA_FIRMA_ATTO";
	String GENERA_FIRMA_REG_CONT = "GENERA_FIRMA_REG_CONT";
	String GENERA_FIRMA_REG_TECN = "GENERA_FIRMA_REG_TECN";
	String FIRMA_REG_TECN = "FIRMA_REG_TECN";
	String RITIRO_FASE_ISTRUTTORIA = "RITIRO_FASE_ISTRUTTORIA";
	
	// Integrazione con JENTE
	String VERIFICA_DATI_CONTABILI	= "VERIFICA_DATI_CONTABILI";
	String RECUPERA_DATI_CONTABILI	= "RECUPERA_DATI_CONTABILI";
	String INVIA_DATI_CONTABILI		= "INVIA_DATI_CONTABILI";
	
	String EDIT_ITER_DD_TO_CON_VERIFICA = "EDIT_ITER_DD_TO_CON_VERIFICA";
	String EDIT_ITER_DD_TO_SENZA_VERIFICA = "EDIT_ITER_DD_TO_SENZA_VERIFICA";
}
