package it.linksmt.assatti.bpm.util;

public interface MessageKeys {

	String PROPOSTA_NON_CONFORME 			= "PROPOSTA_NON_CONFORME";
	String ANNULLA_VISTO_ASSESSORE 			= "ANNULLA_VISTO_ASSESSORE";
	String ANNULLA_VISTO_CONSIGLIERE 		= "ANNULLA_VISTO_CONSIGLIERE";
	
	String REGISTRA_ESITO_SEDUTA_GIUNTA 	= "REGISTRA_ESITO_SEDUTA_GIUNTA";
	String REGISTRA_ESITO_SEDUTA_CONSIGLIO	= "REGISTRA_ESITO_SEDUTA_CONSIGLIO";
	String OTTENUTI_DATI_PUBBLICAZIONE_ALBO = "OTTENUTI_DATI_PUBBLICAZIONE_ALBO";
	
	
	// CASISTICA ELIMINATA
	// String NUMERAZIONE_ATTO					= "NUMERAZIONE_ATTO";
}
