package it.linksmt.assatti.datalayer.domain;

public enum ConfigurazioneTaskEnum {
	RESPONSABILE_TECNICO("DIR_VERIFICA_RESPONSABILE_TECNICO"),
	RESPONSABILE_PROPONENTE("VISTO_RESPONSABILE_ISTRUTTORIA"),
	DIR_SEGRETARIO_COMMISSIONE("DIR_SEGRETARIO_COMMISSIONE"),
	ORD_RESPONSABILE_PROPONENTE("ORD_VISTO_RESPONSABILE_ISTRUTTORIA"),
	DEC_RESPONSABILE_PROPONENTE("DEC_VISTO_RESPONSABILE_ISTRUTTORIA"),
	VERIFICA_RESPONSABILE_TECNICO("VERIFICA_RESPONSABILE_TECNICO"),
	VERIFICA_RESPONSABILE_CONTABILE("VERIFICA_RESPONSABILE_CONTABILE");
	
	private String codice;
	
	private ConfigurazioneTaskEnum(String codice) {
		this.codice = codice;
	}
	
	public String getCodice() {
		return codice;
	}
}
