package it.linksmt.assatti.datalayer.domain;

public enum CriterioRicercaEnum {
	
	UFFICIO_PROPONENTE,
	TUTTI_GLI_UFFICI,
	ATTI_LAVORATI,
	APPARTENENZA_UFFICIO,
	APPARTENENZA_UFFICIO_FULL_VISIB,
	APPARTENENZA_SOTTOSTRUTTURA_FULL_VISIB,
	PROFILI_SOTTOSTRUTTURA_FULL_VISIB,
	LINK_DOC_OMISSIS,
	ACCESSO_ATTO_NEGATO,
	VISIONE_ATTI_GERARCHICA,
	RESP_UFFICI_ATTI_LAVORATI,
	UFFICI_ATTI_LAVORATI,
	

}
