package it.linksmt.assatti.datalayer.domain;

public enum EventoEnum {
	EVENTO_PROPOSTA("PROPOSTA"),
	EVENTO_PROPOSTA_ANNULLATA("PROPOSTA_ANNULLATA"),
	EVENTO_PROPOSTA_INESISTENTE("PROPOSTA_INESISTENTE"),
	EVENTO_PROPOSTA_FIRMATA("PROPOSTA_FIRMATA"),
	EVENTO_ADOZIONE("ADOZIONE"),
	EVENTO_ESECUTIVITA("ESECUTIVITA"),
	EVENTO_ITER_TERMINATO("ITER_TERMINATO"),
	EVENTO_RITIROSUISTANZA("RITIROSUISTANZA"),
	EVENTO_RITIROGIUNTA("RITIROGIUNTA"),
	EVENTO_VERIFICARAGIONERIA("RAGIONERIA"),
	EVENTO_NONESECUTIVITA("NONESECUTIVITA"),
	EVENTO_NOTIFICAINVIATA("NOTIFICA_INVIATA"),
	
	// Eventi pubblicazione
	EVENTO_ATTESA_PUBBLICAZIONE_ALBO("ATTESA_PUBBLICAZIONE_ALBO"),
	EVENTO_ATTESA_PUBBLICAZIONE_TRASPARENZA("ATTESA_PUBBLICAZIONE_TRASPARENZA"),
	EVENTO_ATTO_PUBBLICATO_ALBO("ATTO_PUBBLICATO_ALBO"),
	EVENTO_ATTO_PUBBLICATO_TRASPARENZA("ATTO_PUBBLICATO_TRASPARENZA"),
	EVENTO_RELATA_RECUPERATA("RELATA_RECUPERATA"),
	
	EVENTO_NON_PUBBLICAZIONE_RISERVATO("RISERVATO_NON_PUBBLICATO"),
	EVENTO_PUBBLICAZIONE_TERMINATA("PUBBLICAZIONE_TERMINATA"),
		
	// Eventi registrati su ATTO REVOCATO
	EVENTO_REVOCA("PROVVEDIMENTO_REVOCATO"),
	EVENTO_MODIFICA_INTEGRAZIONE("PROVVEDIMENTO_MODIFICATO_INTEGRATO"),
	EVENTO_PROVVEDIMENTO_COLLEGATO("PROVVEDIMENTO_COLLEGATO"),
	EVENTO_RETTIFICA("PROVVEDIMENTO_RETTIFICATO"),
	EVENTO_REVOCA_RIPROPOSIZIONE("PROVVEDIMENTO_REVOCATO_E_RIPROPOSTO"),
	
	
	//Eventi JEnte
	JENTE_INVIO_DATI_PROPOSTA("JENTE_INVIO_DATI_PROPOSTA");
	
	private String descrizione;
	
	private EventoEnum(String descrizione) {
		this.descrizione = descrizione;
	}
	
	public String getDescrizione() {
		return descrizione;
	}
}