package it.linksmt.assatti.datalayer.domain;

public enum TipoDocumentoSerieEnum {
	DETERMINAZIONI("DETERMINAZIONI"),
	DETERMINAZIONI_PUBBLICATE_ALBO("DETERMINAZIONI_PUBBLICATE_ALBO"),
	PROPOSTE_DETERMINAZIONE("PROPOSTE_DETERMINAZIONE"),
	PARERI("PARERI"),
	ODG("ORDINI_GIORNO"),
	RESOCONTI("RESOCONTI"),
	VERBALI("VERBALI"),
	NOTIFICHE("NOTIFICHE_COMUNICAZIONI"),
	RELATE_DI_PUBBLICAZIONE("RELATE_DI_PUBBLICAZIONE"),
	DELIBERAZIONI_GR("DELIBERAZIONI_GR"),
	DL_APPROVATI("DL_APPROVATI"),
	COMUNICAZIONI_GR("COMUNICAZIONI_GR"),
	SDL_APPROVATI_PRESI_ATTO("SDL_APPROVATI_PRESI_ATTO");
	
	private String value;
	
	private TipoDocumentoSerieEnum(String value) {
		this.value = value;
	}
	
	public String getValue() {
		return value;
	}
}