package it.linksmt.assatti.fdr.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2021-05-25T17:16:02.957+02:00
 * Generated source version: 3.0.10
 * 
 */
@WebService(targetNamespace = "http://service.ws.fdr.linksmt.it/", name = "FdrWsService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FdrWsService {

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse cadesSignature(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth,
        @WebParam(partName = "files", name = "files")
        SignFiles files
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse markFile(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth,
        @WebParam(partName = "markParam", name = "markParam")
        MarkParam markParam
    );

    @WebMethod
    @WebResult(name = "listaProfili", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "listaProfili")
    public ConfigurationResponse cercaProfiliUtenti(
        @WebParam(partName = "filter", name = "filter")
        Profilo filter
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse xadesSignature(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth,
        @WebParam(partName = "files", name = "files")
        SignFiles files,
        @WebParam(partName = "xadesParam", name = "xadesParam")
        XadesParam xadesParam
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse closeSession(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse openSession(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth
    );

    @WebMethod
    @WebResult(name = "verificationResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "verificationResponse")
    public FdrWsResponse checkSignature(
        @WebParam(partName = "auth", name = "auth")
        VerificationAuth auth,
        @WebParam(partName = "param", name = "param")
        FdrParam param
    );

    @WebMethod
    @WebResult(name = "verificationResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "verificationResponse")
    public FdrWsResponse checkMarkTime(
        @WebParam(partName = "auth", name = "auth")
        VerificationAuth auth,
        @WebParam(partName = "param", name = "param")
        FdrParam param
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse addCadesSignature(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth,
        @WebParam(partName = "param", name = "param")
        FdrParam param
    );

    @WebMethod
    @WebResult(name = "signatureResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "signatureResponse")
    public FdrWsResponse padesSignature(
        @WebParam(partName = "auth", name = "auth")
        SignatureAuth auth,
        @WebParam(partName = "files", name = "files")
        SignPdfFiles files,
        @WebParam(partName = "padesParam", name = "padesParam")
        PadesParam padesParam
    );

    @WebMethod
    @WebResult(name = "baseResponse", targetNamespace = "http://service.ws.fdr.linksmt.it/", partName = "baseResponse")
    public BaseResponse sendCredential(
        @WebParam(partName = "auth", name = "auth")
        SupportAuth auth
    );
}
