package it.linksmt.assatti.fdr.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2021-05-25T17:16:02.990+02:00
 * Generated source version: 3.0.10
 * 
 */
@WebServiceClient(name = "FdrWsServiceImplService", 
                  wsdlLocation = "file:/opt/dev/ATTICO/source/assatti/assatti-cooperation/assatti-fdr-client/src/main/resources/fdrwsservice.wsdl",
                  targetNamespace = "http://impl.service.ws.fdr.linksmt.it/") 
public class FdrWsServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.ws.fdr.linksmt.it/", "FdrWsServiceImplService");
    public final static QName FdrWsServiceImplPort = new QName("http://impl.service.ws.fdr.linksmt.it/", "FdrWsServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/opt/dev/ATTICO/source/assatti/assatti-cooperation/assatti-fdr-client/src/main/resources/fdrwsservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FdrWsServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/opt/dev/ATTICO/source/assatti/assatti-cooperation/assatti-fdr-client/src/main/resources/fdrwsservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FdrWsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FdrWsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FdrWsServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FdrWsServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FdrWsServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FdrWsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns FdrWsService
     */
    @WebEndpoint(name = "FdrWsServiceImplPort")
    public FdrWsService getFdrWsServiceImplPort() {
        return super.getPort(FdrWsServiceImplPort, FdrWsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FdrWsService
     */
    @WebEndpoint(name = "FdrWsServiceImplPort")
    public FdrWsService getFdrWsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FdrWsServiceImplPort, FdrWsService.class, features);
    }

}
