package it.linksmt.assatti.utility;

public interface RoleCodes {
	
	String ROLE_SEGRETARIO_SEDUTA_GIUNTA 		= "ROLE_SEGRETARIO_SEDUTA_GIUNTA";
	String ROLE_SEGRETARIO_SEDUTA_CONSIGLIO		= "ROLE_SEGRETARIO_SEDUTA_CONSIGLIO";
	String ROLE_PRESIDENTE_SEDUTA_GIUNTA 		= "ROLE_PRESIDENTE_SEDUTA_GIUNTA";
	String ROLE_PRESIDENTE_SEDUTA_CONSIGLIO		= "ROLE_PRESIDENTE_SEDUTA_CONSIGLIO";
	String ROLE_VICE_PRESIDENTE_SEDUTA_GIUNTA	= "ROLE_VICE_PRESIDENTE_SEDUTA_GIUNTA";
	String ROLE_VICE_PRESIDENTE_SEDUTA_CONSIGLIO= "ROLE_VICE_PRESIDENTE_SEDUTA_CONSIGLIO";
	String ROLE_COMPONENTE_GIUNTA 				= "ROLE_COMPONENTE_GIUNTA";
	String ROLE_COMPONENTE_CONSIGLIO			= "ROLE_COMPONENTE_CONSIGLIO";
	String ROLE_SUPERVISORE_CONSULTAZIONE_ATTI	= "ROLE_SUPERVISORE_CONSULTAZIONE_ATTI";
	String ROLE_OPERATORE_SEGRETERIA_GIUNTA 	= "ROLE_OPERATORE_SEGRETERIA_GIUNTA";
	String ROLE_OPERATORE_SEGRETERIA_CONSIGLIO 	= "ROLE_OPERATORE_SEGRETERIA_CONSIGLIO";
	String ROLE_SEGRETARIO_GENERALE 			= "ROLE_SEGRETARIO_GENERALE";
}
